version: '3'

services:
  vue-project:
    container_name: vue-project_dev_aybot
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - "5173:5173"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
